# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\slideshow_main.ui'
#
# Created: Mon Apr 14 21:05:56 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 604)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(5, -1, 5, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_image = QtGui.QLabel(self.centralwidget)
        self.lbl_image.setText("")
        self.lbl_image.setScaledContents(False)
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setWordWrap(False)
        self.lbl_image.setMargin(0)
        self.lbl_image.setObjectName("lbl_image")
        self.gridLayout.addWidget(self.lbl_image, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_prev = QtGui.QPushButton(self.centralwidget)
        self.btn_prev.setEnabled(False)
        self.btn_prev.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_prev.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_prev.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/media-seek-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon1)
        self.btn_prev.setIconSize(QtCore.QSize(32, 32))
        self.btn_prev.setDefault(False)
        self.btn_prev.setFlat(False)
        self.btn_prev.setObjectName("btn_prev")
        self.horizontalLayout.addWidget(self.btn_prev)
        self.btn_play = QtGui.QPushButton(self.centralwidget)
        self.btn_play.setEnabled(False)
        self.btn_play.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_play.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_play.setText("")
        self.btn_play.setIcon(icon)
        self.btn_play.setIconSize(QtCore.QSize(32, 32))
        self.btn_play.setDefault(False)
        self.btn_play.setFlat(False)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_next = QtGui.QPushButton(self.centralwidget)
        self.btn_next.setEnabled(False)
        self.btn_next.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_next.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_next.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/media-seek-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon2)
        self.btn_next.setIconSize(QtCore.QSize(32, 32))
        self.btn_next.setDefault(False)
        self.btn_next.setFlat(False)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_delete = QtGui.QPushButton(self.centralwidget)
        self.btn_delete.setEnabled(False)
        self.btn_delete.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_delete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon3)
        self.btn_delete.setIconSize(QtCore.QSize(32, 32))
        self.btn_delete.setDefault(False)
        self.btn_delete.setFlat(False)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuSlideshow_speed = QtGui.QMenu(self.menuOption)
        self.menuSlideshow_speed.setObjectName("menuSlideshow_speed")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.status_bar = QtGui.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.action_recursive = QtGui.QAction(MainWindow)
        self.action_recursive.setCheckable(True)
        self.action_recursive.setObjectName("action_recursive")
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.action_speed_slow = QtGui.QAction(MainWindow)
        self.action_speed_slow.setCheckable(True)
        self.action_speed_slow.setObjectName("action_speed_slow")
        self.action_speed_medium = QtGui.QAction(MainWindow)
        self.action_speed_medium.setCheckable(True)
        self.action_speed_medium.setObjectName("action_speed_medium")
        self.action_speed_fast = QtGui.QAction(MainWindow)
        self.action_speed_fast.setCheckable(True)
        self.action_speed_fast.setObjectName("action_speed_fast")
        self.action_speed_custom = QtGui.QAction(MainWindow)
        self.action_speed_custom.setCheckable(True)
        self.action_speed_custom.setObjectName("action_speed_custom")
        self.action_about_slideshow = QtGui.QAction(MainWindow)
        self.action_about_slideshow.setObjectName("action_about_slideshow")
        self.action_about_pyside = QtGui.QAction(MainWindow)
        self.action_about_pyside.setObjectName("action_about_pyside")
        self.action_fullscreen = QtGui.QAction(MainWindow)
        self.action_fullscreen.setCheckable(True)
        self.action_fullscreen.setObjectName("action_fullscreen")
        self.menuFile.addAction(self.action_open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        self.menuSlideshow_speed.addAction(self.action_speed_slow)
        self.menuSlideshow_speed.addAction(self.action_speed_medium)
        self.menuSlideshow_speed.addAction(self.action_speed_fast)
        self.menuSlideshow_speed.addAction(self.action_speed_custom)
        self.menuOption.addAction(self.action_recursive)
        self.menuOption.addAction(self.action_fullscreen)
        self.menuOption.addAction(self.menuSlideshow_speed.menuAction())
        self.menuAbout.addAction(self.action_about_slideshow)
        self.menuAbout.addAction(self.action_about_pyside)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_play, self.btn_next)
        MainWindow.setTabOrder(self.btn_next, self.btn_prev)
        MainWindow.setTabOrder(self.btn_prev, self.btn_delete)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Slideshow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_prev.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous image", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_play.setToolTip(QtGui.QApplication.translate("MainWindow", "Start slideshow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_next.setToolTip(QtGui.QApplication.translate("MainWindow", "Next image", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_delete.setToolTip(QtGui.QApplication.translate("MainWindow", "Delete Image", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOption.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSlideshow_speed.setTitle(QtGui.QApplication.translate("MainWindow", "Slideshow speed", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.action_recursive.setText(QtGui.QApplication.translate("MainWindow", "Include subfolders", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "Open directory", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_speed_slow.setText(QtGui.QApplication.translate("MainWindow", "Slow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_speed_medium.setText(QtGui.QApplication.translate("MainWindow", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.action_speed_fast.setText(QtGui.QApplication.translate("MainWindow", "Fast", None, QtGui.QApplication.UnicodeUTF8))
        self.action_speed_custom.setText(QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about_slideshow.setText(QtGui.QApplication.translate("MainWindow", "About Slideshow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about_pyside.setText(QtGui.QApplication.translate("MainWindow", "About PySide", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fullscreen.setText(QtGui.QApplication.translate("MainWindow", "Fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fullscreen.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
