# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\slideshow_main.ui'
#
# Created: Sun Apr  6 05:03:16 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 604)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.image = QtGui.QLabel(self.centralwidget)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.btnPrev = QtGui.QPushButton(self.centralwidget)
        self.btnPrev.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnPrev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/media-seek-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrev.setIcon(icon)
        self.btnPrev.setIconSize(QtCore.QSize(32, 32))
        self.btnPrev.setObjectName("btnPrev")
        self.horizontalLayout.addWidget(self.btnPrev)
        self.btnPlay = QtGui.QPushButton(self.centralwidget)
        self.btnPlay.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btnPlay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlay.setIcon(icon1)
        self.btnPlay.setIconSize(QtCore.QSize(32, 32))
        self.btnPlay.setObjectName("btnPlay")
        self.horizontalLayout.addWidget(self.btnPlay)
        self.btnNext = QtGui.QPushButton(self.centralwidget)
        self.btnNext.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnNext.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/media-seek-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon2)
        self.btnNext.setIconSize(QtCore.QSize(32, 32))
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout.addWidget(self.btnNext)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnDelete = QtGui.QPushButton(self.centralwidget)
        self.btnDelete.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnDelete.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon3)
        self.btnDelete.setIconSize(QtCore.QSize(32, 32))
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuSlideshow_speed = QtGui.QMenu(self.menuOption)
        self.menuSlideshow_speed.setObjectName("menuSlideshow_speed")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionInclude_subfolders = QtGui.QAction(MainWindow)
        self.actionInclude_subfolders.setCheckable(True)
        self.actionInclude_subfolders.setObjectName("actionInclude_subfolders")
        self.actionOpen_directory = QtGui.QAction(MainWindow)
        self.actionOpen_directory.setObjectName("actionOpen_directory")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSlow = QtGui.QAction(MainWindow)
        self.actionSlow.setCheckable(True)
        self.actionSlow.setObjectName("actionSlow")
        self.actionMedium = QtGui.QAction(MainWindow)
        self.actionMedium.setCheckable(True)
        self.actionMedium.setObjectName("actionMedium")
        self.actionFast = QtGui.QAction(MainWindow)
        self.actionFast.setCheckable(True)
        self.actionFast.setObjectName("actionFast")
        self.actionCustom = QtGui.QAction(MainWindow)
        self.actionCustom.setCheckable(True)
        self.actionCustom.setObjectName("actionCustom")
        self.actionAbout_Slideshow = QtGui.QAction(MainWindow)
        self.actionAbout_Slideshow.setObjectName("actionAbout_Slideshow")
        self.actionAbout_PySide = QtGui.QAction(MainWindow)
        self.actionAbout_PySide.setObjectName("actionAbout_PySide")
        self.menuFile.addAction(self.actionOpen_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSlideshow_speed.addAction(self.actionSlow)
        self.menuSlideshow_speed.addAction(self.actionMedium)
        self.menuSlideshow_speed.addAction(self.actionFast)
        self.menuSlideshow_speed.addAction(self.actionCustom)
        self.menuOption.addAction(self.actionInclude_subfolders)
        self.menuOption.addAction(self.menuSlideshow_speed.menuAction())
        self.menuAbout.addAction(self.actionAbout_Slideshow)
        self.menuAbout.addAction(self.actionAbout_PySide)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnPlay, self.btnNext)
        MainWindow.setTabOrder(self.btnNext, self.btnPrev)
        MainWindow.setTabOrder(self.btnPrev, self.btnDelete)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Slideshow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrev.setToolTip(QtGui.QApplication.translate("MainWindow", "Previous image", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlay.setToolTip(QtGui.QApplication.translate("MainWindow", "Start slideshow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNext.setToolTip(QtGui.QApplication.translate("MainWindow", "Next image", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setToolTip(QtGui.QApplication.translate("MainWindow", "Delete Image", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOption.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSlideshow_speed.setTitle(QtGui.QApplication.translate("MainWindow", "Slideshow speed", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInclude_subfolders.setText(QtGui.QApplication.translate("MainWindow", "Include subfolders", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_directory.setText(QtGui.QApplication.translate("MainWindow", "Open directory", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSlow.setText(QtGui.QApplication.translate("MainWindow", "Slow", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMedium.setText(QtGui.QApplication.translate("MainWindow", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFast.setText(QtGui.QApplication.translate("MainWindow", "Fast", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCustom.setText(QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Slideshow.setText(QtGui.QApplication.translate("MainWindow", "About Slideshow", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_PySide.setText(QtGui.QApplication.translate("MainWindow", "About PySide", None, QtGui.QApplication.UnicodeUTF8))
